"""renamed has_moon

Revision ID: 5662cea0f0b3
Revises: 1e71069e2045
Create Date: 2022-05-02 16:56:58.711477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5662cea0f0b3'
down_revision = '1e71069e2045'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('has_moon', sa.Boolean(), nullable=True))
    op.drop_column('planet', 'has_mooon')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('has_mooon', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('planet', 'has_moon')
    # ### end Alembic commands ###
